namespace: lantronix
name: lmos
version: 1.0.1
readme: README.md
description: Ansible collection for Lantronix LMOS (Local Manager OS) devices
license:
  - Apache-2.0
authors:
  - Lantronix Product Team <ansible@lantronix.com>
repository: https://github.com/Lantronix/ansible-collection-lmos
documentation: https://github.com/Lantronix/ansible-collection-lmos#readme
homepage: https://www.lantronix.com
issues: https://github.com/Lantronix/ansible-collection-lmos/issues
tags:
  - networking
  - lantronix
  - lmos
  - uplogix
  - console_server
  - local_manager
build_ignore:
  - "*.tar.gz"
  - .venv
  - .ansible
  - "tests*"
dependencies:
  ansible.netcommon: ">=5.0.0"
